### 
# Replace the value of `Authorization` header with your token.
# Example:
# Authorization: Bearer your_actual_token_here
###
POST http://localhost:9000/api/expenses
Content-Type: application/json
Authorization: Bearer 1|O0y5pbK4sTml9ddA59dOXMLrtPVYQKsnDS1dNycI3adb57fb

{
  "description": "Compra de Material de Escritório",
  "date": "2024-07-23",
  "value": 100.50
}