### 
# Replace the value of `Authorization` header with your token.
# Example:
# Authorization: Bearer your_actual_token_here
###
GET http://localhost:8000/api/expenses/2
Authorization: Bearer 4|bTUrHTBLhQ8JQ3sGKAQUsOIafEqkPE6uIXQX7iR0352c7853
