### 
# Replace the value of `Authorization` header with your token.
# Example:
# Authorization: Bearer your_actual_token_here
###
PUT http://localhost:8000/api/expenses/2
Content-Type: application/json
Authorization: Bearer 4|bTUrHTBLhQ8JQ3sGKAQUsOIafEqkPE6uIXQX7iR0352c7853

{
  "description": "Compra de Material de Escritório Atualizada",
  "date": "2024-07-23",
  "value": 150.85
}